### ISSUE TITLE
Translate “09 Classes”

### ISSUE THREAD

**Issue by denysdovhan** [denysdovhan/understandinges6ua#10]
Translate [`09-Classes.md`](https://github.com/nzakas/understandinges6/blob/master/manuscript/09-Classes.md).

**Comment by victorpavlov** [comment]
@denysdovhan Hello! I would like translate this chapter.

**Comment by denysdovhan** [comment]
Sure, go ahead!

**Comment by denysdovhan** [comment]
@victorpavlov what's up?

**Comment by victorpavlov** [comment]
@denysdovhan Hi! I'm fine, but have some work now. If you need this to review I can speed up. Should I?

**Comment by denysdovhan** [comment]
@victorpavlov nope, it's okay. I just ask to be updated what is going on.

**Comment by denysdovhan** [comment]
@victorpavlov do you have any updates?

**Comment by victorpavlov** [comment]
@denysdovhan Yes, I'm in progress, but not finished yet. Approximately 30% of chapter is done. Sorry, but... Summer :)

**Comment by denysdovhan** [comment]
Well, it's okay. I'm gonna force translation. I want to finish the translation to the end of the summer.

**Comment by victorpavlov** [comment]
Understood, I'll do my best.
