### ISSUE TITLE
Привіт

### ISSUE THREAD

**Issue by Volodymyr-Yarymovych** [denysdovhan/understandinges6ua#129]
Привіт,я розробляю український сервер для minecraft!В цьому проєкті буде багато міні ігор та багато іншого,але сам я не впораюсь тому шукаю команду!Потрібні люди які вміють писати плагіни,робити ресурс паки або сайти або гарно будувати!Детальніша інформація у діскорд Вовa#5204 (a агнлійська)!Буду радий вашій допомозі!Запевняю вас це буде дуже маштабний проєкт.Дякую за увагу!

**Comment by denysdovhan** [comment]
Здається це не за адресою :)

**Comment by Volodymyr-Yarymovych** [comment]
> Здається це не за адресою :)

Ну не знаю,може хтось побачить)

**Comment by Vovacr** [comment]
Привіт,я розробляю український сервер для minecraft!В цьому проєкті буде багато міні ігор та багато іншого,але сам я не впораюсь тому шукаю команду!Потрібні люди які вміють писати плагіни,робити ресурс паки або сайти або гарно будувати!Детальніша інформація у діскорд Вовa#5204 (a агнлійська)!Буду радий вашій допомозі!Запевняю вас це буде дуже маштабний проєкт.Дякую за увагу!
