### ISSUE TITLE
Translate “13 Modules”

### ISSUE THREAD

**Issue by denysdovhan** [denysdovhan/understandinges6ua#13]
Translate [`14-Modules.md`](https://github.com/nzakas/understandinges6/blob/master/manuscript/14-Modules.md).

**Comment by victorpavlov** [comment]
@denysdovhan Can I take this chapter?

**Comment by denysdovhan** [comment]
Yep, sure. Don't forget to make new branch and add commit original text, before you start to translate.

**Comment by victorpavlov** [comment]
@denysdovhan, sure, now I'm not a new one :)

**Comment by victorpavlov** [comment]
@denysdovhan I've started translation of the chapter, but in the original repo some changes happens. Not this chanter has number 13 https://github.com/nzakas/understandinges6/tree/master/manuscript. What should I do?

**Comment by denysdovhan** [comment]
@victorpavlov it's okay. Just rename this chapter and translate the new version.
