### ISSUE TITLE
НВФВ чи МВФВ

### ISSUE THREAD

**Issue by LeusMaximus** [denysdovhan/understandinges6ua#44]
В розділі "ФункціЇ" згадується вираз "миттєво–виконуваний функціональний вираз" (МВФВ).
В той час як в розділі "Блочне звʼязування" використовується вираз "негайно виконуваний функціональний вираз (НВФВ)".
Пропоную використовувати однаковий термін для цього.

**Comment by denysdovhan** [comment]
@terrysahaidak @victorpavlov давайте вирішувати.

**Comment by terrysahaidak** [comment]
Ну миттєво -- це тобто дуже швидко, тобто більше про час виконання. А негайно -- про час, коли коли подія настала -- вже зараз. Тому, імхо, негайно біль підходить у даному контексті.

**Comment by victorpavlov** [comment]
@denysdovhan @terrysahaidak @LeusMaximus Гадаю, що `негайно` буде краще.

**Comment by denysdovhan** [comment]
Гаразд, тоді НВФВ. Постараюсь якнайшвидше виправити розділи.
